// P0010.2.5 — One-shot cleanup of polluted Situation rows.
//
// Audit (2026-08-27) found 39 situations in the database. Classification:
//
//   TEST_DATA        (6) — explicit test fixtures / demos
//     sit_observe_demo, sit_human_demo, sit_failed_recover_demo, sit_waiting_human_demo
//     sit_recover_2cyc_001, sit_kill_during_investigation_test
//
//   BUG_GENERATED   (14) — generated by earlier code bugs / test fixtures
//     10 unknown-SKU ranking_attention (SKUs 10072459317818, 10072459153406
//       repeated across 5 days — products with no real catalog name)
//     4 "100% drops" from 2026-08-22 (gmv→0, orders→0, uv→0, cvr→0%
//       — values the live fixture never produced, so these came from
//       a transient ingestion bug)
//
//   VALID_CURRENT (4)  — 4 fresh "祁门红茶旗舰店 成交金额 较昨日下降" from
//     the P0010.2.4 perf test (Aug 27) — kept; they are in the
//     production chain.
//
//   VALID_HISTORICAL (15) — older meaningful_change / cross_signal
//     observations for 祁门红茶旗舰店 that have real business meaning.
//
// This script deletes the 20 polluted rows, cascading to their
// human_interventions, learning_contexts, and the matching JSON
// files in data/fabric-workspace/{situations,investigations}/.
//
// Idempotency: re-running the script on an already-cleaned DB is a
// no-op (no rows match the deletion set).
//
// Usage:
//   npx tsx scripts/cleanup-polluted-situations.ts            # apply
//   npx tsx scripts/cleanup-polluted-situations.ts --dry-run  # preview only

import { readdirSync, unlinkSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { openDb, closeDb } from '../platform/storage/connection.js';

interface CleanupTarget {
  situationId: string;
  classification: 'TEST_DATA' | 'BUG_GENERATED';
  reason: string;
}

const TARGETS: readonly CleanupTarget[] = [
  // ---- TEST_DATA — explicit test fixtures / demos ----
  { situationId: 'sit_observe_demo',                    classification: 'TEST_DATA',     reason: 'description has "_demo" suffix; demo fixture' },
  { situationId: 'sit_human_demo',                      classification: 'TEST_DATA',     reason: 'description has "_demo" suffix; demo fixture' },
  { situationId: 'sit_failed_recover_demo',             classification: 'TEST_DATA',     reason: 'description has "_demo" suffix; demo fixture' },
  { situationId: 'sit_waiting_human_demo',              classification: 'TEST_DATA',     reason: 'description has "_demo" suffix; demo fixture' },
  { situationId: 'sit_recover_2cyc_001',                classification: 'TEST_DATA',     reason: 'description is "2-cycle test: pre-existing pending situation from before server restart"' },
  { situationId: 'sit_kill_during_investigation_test',  classification: 'TEST_DATA',     reason: 'description is "kill-during-investigation test: simulate process death 15min ago mid-turn"' },

  // ---- BUG_GENERATED — unknown-SKU ranking_attention (5 days × 2 products) ----
  // Prevention: rules.ts now skips these via the unknown-SKU filter. See
  // detectRankingAttention in apps/ecommerce/runtime/situation/rules.ts.
  { situationId: 'sit_6d6b5ec1d7402bd92518',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459317818 — no real catalog name' },
  { situationId: 'sit_939bfaea6422c90a96fb',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459153406 — no real catalog name' },
  { situationId: 'sit_63247bce6e70bb6bad9a',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459317818 — no real catalog name' },
  { situationId: 'sit_187fa87be7a62fd58aae',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459153406 — no real catalog name' },
  { situationId: 'sit_bb96b0d781c532bf080e',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459317818 — no real catalog name' },
  { situationId: 'sit_003b9c4485177f642a74',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459153406 — no real catalog name' },
  { situationId: 'sit_8e091571d798eaf0d994',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459317818 — no real catalog name' },
  { situationId: 'sit_3cb1b4bd69f15eef6367',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459153406 — no real catalog name' },
  { situationId: 'sit_ebefd40b955fe50d92ab',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459317818 — no real catalog name' },
  { situationId: 'sit_80e647bab4db7bc9383f',  classification: 'BUG_GENERATED', reason: 'ranking_attention for SKU 10072459153406 — no real catalog name' },

  // ---- BUG_GENERATED — 100% drops on 2026-08-22 (transient ingestion bug) ----
  // The live fixture never produced values of exactly 0 for gmv/orders/uv/
  // cvr in a single day; the simultaneous 100% drops across all 4 metrics
  // indicate the producer was given an empty/broken daily_summary signal.
  { situationId: 'sit_700cf7123ff8d1b671cf',  classification: 'BUG_GENERATED', reason: 'meaningful_change gmv 100% drop to ¥0.00 on 2026-08-22 — fixture ingestion bug' },
  { situationId: 'sit_1969ad32c8c95b434625',  classification: 'BUG_GENERATED', reason: 'meaningful_change orders 100% drop to 0 on 2026-08-22 — fixture ingestion bug' },
  { situationId: 'sit_3da751a0765c923e2de8',  classification: 'BUG_GENERATED', reason: 'meaningful_change uv 100% drop to 0 on 2026-08-22 — fixture ingestion bug' },
  { situationId: 'sit_71dddfb384f2211fba51',  classification: 'BUG_GENERATED', reason: 'meaningful_change cvr 100% drop to 0% on 2026-08-22 — fixture ingestion bug' },
];

const main = (): void => {
  const dryRun = process.argv.includes('--dry-run');
  const workspaceDir = resolve(process.cwd(), 'data', 'fabric-workspace');
  const situationsDir = join(workspaceDir, 'situations');
  const investigationsDir = join(workspaceDir, 'investigations');
  const db = openDb();

  console.log(`[cleanup] P0010.2.5 polluted-situation purge — ${dryRun ? 'DRY RUN' : 'APPLY'}`);
  console.log(`[cleanup] DB: ${process.env.DB_PATH ?? './data/agentfabric.db'}`);
  console.log(`[cleanup] Targets: ${TARGETS.length} situations`);
  console.log('');

  // Group counts by classification for the summary.
  const byClass: Record<string, number> = { TEST_DATA: 0, BUG_GENERATED: 0 };
  for (const t of TARGETS) byClass[t.classification] = (byClass[t.classification] ?? 0) + 1;
  console.log('[cleanup] Classification breakdown:');
  for (const [k, v] of Object.entries(byClass)) console.log(`  - ${k}: ${v}`);

  // Probe before: which targets actually exist?
  const idList = TARGETS.map((t) => t.situationId);
  const placeholders = idList.map(() => '?').join(',');
  const existing = db
    .prepare(`SELECT situation_id, lifecycle FROM situations WHERE situation_id IN (${placeholders})`)
    .all(...idList) as Array<{ situation_id: string; lifecycle: string }>;
  console.log(`[cleanup] Existing in DB: ${existing.length}/${TARGETS.length}`);

  // FK cascade plan: human_interventions → learning_contexts → situations
  const counts = { interventions: 0, learningContexts: 0, situations: 0, jsonFiles: 0 };

  if (!dryRun) {
    const tx = db.transaction((ids: readonly string[]) => {
      const intRes = db
        .prepare(`DELETE FROM human_interventions WHERE situation_id = ?`)
        .run(ids[0]!);
      // Better-sqlite3's `run` does not support array params directly;
      // do the FK-safe delete one row at a time inside the transaction.
      // For 20 rows this is well under 1ms; clarity > cleverness.
      let totalInt = 0;
      let totalLc = 0;
      let totalSit = 0;
      for (const id of ids) {
        totalInt += db.prepare(`DELETE FROM human_interventions WHERE situation_id = ?`).run(id).changes;
        totalLc += db.prepare(`DELETE FROM learning_contexts WHERE situation_id = ?`).run(id).changes;
        totalSit += db.prepare(`DELETE FROM situations WHERE situation_id = ?`).run(id).changes;
      }
      counts.interventions = totalInt;
      counts.learningContexts = totalLc;
      counts.situations = totalSit;
      // intRes kept to silence unused warning; final counts are authoritative.
      void intRes;
      return { totalInt, totalLc, totalSit };
    });
    tx(idList);
  }

  // JSON files in fabric-workspace/{situations,investigations}/. These are
  // written by the projector from learning_contexts.body; after we delete
  // the rows, the files are stale and confusing for an operator browsing
  // the workspace. Clean them in lockstep.
  const filesToDelete: string[] = [];
  for (const t of TARGETS) {
    for (const dir of [situationsDir, investigationsDir]) {
      if (!existsSync(dir)) continue;
      for (const f of readdirSync(dir)) {
        if (f.startsWith(t.situationId)) filesToDelete.push(join(dir, f));
      }
    }
  }
  if (!dryRun) {
    for (const f of filesToDelete) {
      try { unlinkSync(f); counts.jsonFiles++; } catch { /* best-effort */ }
    }
  }

  // Probe after: how many situations remain in the DB?
  const remaining = (db.prepare(`SELECT COUNT(*) AS c FROM situations`).get() as { c: number }).c;
  const remainingOpen = (db
    .prepare(`SELECT COUNT(*) AS c FROM situations WHERE lifecycle = 'open'`)
    .get() as { c: number }).c;

  console.log('');
  console.log('[cleanup] Deleted:');
  console.log(`  - situations:           ${counts.situations}`);
  console.log(`  - learning_contexts:    ${counts.learningContexts}`);
  console.log(`  - human_interventions:  ${counts.interventions}`);
  console.log(`  - workspace json files: ${counts.jsonFiles}`);
  console.log('');
  console.log(`[cleanup] After: ${remaining} situations in DB (${remainingOpen} open / ${remaining - remainingOpen} terminal).`);

  closeDb(db);
};

main();
